# Generated by Django 5.2.8 on 2025-11-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_libro', models.PositiveIntegerField(unique=True)),
                ('titulo', models.CharField(max_length=160, unique=True)),
                ('isbn', models.PositiveIntegerField(max_length=13)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('anio_publicacion', models.PositiveBigIntegerField(max_length=4)),
                ('categoria', models.CharField(max_length=100)),
                ('num_paginas', models.PositiveBigIntegerField(max_length=4)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('copias_disponibles', models.PositiveBigIntegerField(max_length=50)),
            ],
            options={
                'ordering': ('id_libro',),
            },
        ),
    ]
