# Generated by Django 5.2.8 on 2025-11-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id_libro',
        ),
    ]
