# Generated by Django 5.2.8 on 2025-11-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_libro_options_remove_libro_id_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anio_publicacion',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='copias_disponibles',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_paginas',
            field=models.PositiveBigIntegerField(),
        ),
    ]
