# Generated by Django 5.2.8 on 2025-11-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_libro_anio_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={},
        ),
        migrations.AlterField(
            model_name='libro',
            name='anio_publicacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libro',
            name='copias_disponibles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(help_text='Ej: Disponible, Prestado, Dañado', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_paginas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ubicacion',
            field=models.CharField(help_text='Ej: Estantería A3, Piso 2', max_length=100),
        ),
    ]
